Page({
  data: {
    goodsList: [{
      id: '0',
      image_url: '/image/test01.png',
      description: 'hinkPaid的测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字',
      price: '10.9',
      rentStart: '一月起租',
      priceInt: 10,
      pricefloat: 9
    }, {
      id: '0',
      image_url: '/image/test01.png',
      description: 'hinkPaid的测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字',
      price: '10.9',
      rentStart: '一月起租',
      priceInt: 10,
      pricefloat: 9
    }, {
      id: '0',
      image_url: '/image/test01.png',
      description: 'hinkPaid的测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字',
      price: '10.9',
      rentStart: '一月起租',
      priceInt: 10,
      pricefloat: 9
    }, {
      id: '0',
      image_url: '/image/test01.png',
      description: 'ThinkPaid的测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字',
      price: '10.9',
      rentStart: '一月起租',
      priceInt: 10,
      pricefloat: 9
    }, {
      id: '0',
      image_url: '/image/test01.png',
      description: 'hinkPaid的测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字',
      price: '10.9',
      rentStart: '一月起租',
      priceInt: 10,
      pricefloat: 9
    }, {
      id: '0',
      image_url: '/image/test01.png',
      description: 'hinkPaid的测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字测试文字',
      price: '10.9',
      rentStart: '一月起租',
      priceInt: 10,
      pricefloat: 9
    }]
  },
  onLoad() {},
});